name: Metrics
on:
  schedule: [{ cron: "0 0 * * 1" }] # every Monday
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: activity
          config_timezone: Europe/Berlin
